In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a, '|', type(a))

[1 2 3] | <class 'numpy.ndarray'>


In [3]:
a.dtype

dtype('int32')

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a, '|', type(a))

[[1. 2. 3.]
 [4. 5. 6.]] | <class 'numpy.ndarray'>


In [5]:
a[0]

array([1., 2., 3.])

In [6]:
a[1,2]

6.0

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(4)

array([7.59037894e-311, 6.34264542e-311, 2.80740043e-311, 1.59361884e-311])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [12]:
# от 0 до 10, 5 чисел с равным шагом
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
rng = np.random.default_rng(0)
rng.integers(5, size=(2, 4))

array([[4, 3, 2, 1],
       [1, 0, 0, 0]], dtype=int64)

In [14]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
rng.random((3, 2))

array([[0.81327024, 0.91275558],
       [0.60663578, 0.72949656],
       [0.54362499, 0.93507242]])

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# Вы можете быстро отсортировать числа в порядке возрастания с помощью:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.array([1, 2, 3])
# берем элементы на первом и 2 индексе
a = a[[1, 2]]
a

array([2, 3])

In [19]:
np.append(a, np.array([4, 5, 6, 7]))

array([2, 3, 4, 5, 6, 7])

In [20]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [21]:
np.concatenate((a,b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [22]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [23]:
a = np.array([1, 2, 3])
b = a
c =  a.copy()

# меняем 0й элемент
a[0] = 0

print(f'Измененный массив а {a}')
print(f'Измененный массив b {b}  <-- изменился по ссылке т.к. поменяти 0й элемент а')
print(f'Измененный массив c {c}  <-- создали копию в памяти')

Измененный массив а [0 2 3]
Измененный массив b [0 2 3]  <-- изменился по ссылке т.к. поменяти 0й элемент а
Измененный массив c [1 2 3]  <-- создали копию в памяти
