In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [2]:
train_data = pd.read_csv("train.csv")
train_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  58036  18387       2     175    75.0    110     70            1     1   
1  88981  23328       2     155    66.0    140     90            1     1   
2  74325  17602       2     168    73.0    120     80            2     1   
3  16519  23432       2     183    95.0    140     90            1     1   
4  28981  23162       1     156    62.0    150     80            1     1   

   smoke  alco  active  cardio  
0      0     0       1       1  
1      1     1       0       0  
2      0     0       1       0  
3      0     0       0       1  
4      0     0       1       1

In [3]:
test_data = pd.read_csv("test.csv")
test_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  36043  17646       2     165    65.0    120     80            1     1   
1  44455  20418       1     161    77.0    120     70            1     1   
2  61323  20347       1     165    88.0    120     80            2     2   
3  27780  18086       2     170    91.0    120     80            3     3   
4  54273  21791       1     158    67.0    130     80            1     1   

   smoke  alco  active  cardio  
0      0     0       0       1  
1      0     0       1       1  
2      0     0       1       1  
3      0     0       1       1  
4      0     0       1       1

In [4]:
X_train = train_data.drop(columns=['cardio'])
Y_train = train_data['cardio']

In [5]:
X_test = test_data.drop(columns=['cardio'])
Y_test = test_data['cardio']

In [6]:
logreg = LogisticRegression()

In [7]:
logreg.fit(X_train, Y_train)

D:\Projects_py\Django_NuxtJS\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [8]:
y_predicted_logreg = logreg.predict(X_test)

In [9]:
y_predicted_logreg

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [10]:
y_predicted_logreg[:10]

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [11]:
np.array(Y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf = RandomForestClassifier(n_estimators=20, max_depth=10)

In [14]:
rf.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, n_estimators=20)

In [15]:
y_predicted_rf = rf.predict(X_test)

In [16]:
y_predicted_rf[:10]

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [17]:
np.array(Y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_predicted_logreg, Y_test)

0.6958333333333333

In [20]:
accuracy_score(y_predicted_rf, Y_test)

0.7335833333333334

In [21]:
from sklearn.metrics import f1_score

In [22]:
f1_score(y_predicted_logreg, Y_test)

0.6857782369146006

In [23]:
f1_score(y_predicted_rf, Y_test)

0.7227473766368917

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

In [25]:
data = pd.read_csv("melb_data.csv")
data.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [26]:
answer = data['Price']
data = data.drop(columns=['Price'])

In [27]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(data, answer, test_size=0.2)


In [40]:
# Car, BuildingArea и YearBuilt — числовые признаки, поэтому заполняем пропуски медианами по столбцам
X_train['Car'] = X_train['Car'].fillna(X_train['Car'].median())
X_train['BuildingArea'] = X_train['BuildingArea'].fillna(X_train['BuildingArea'].median())
X_train['YearBuilt'] = X_train['YearBuilt'].fillna(X_train['YearBuilt'].median())

# CouncilArea — категориальный признак, поэтому заполним наны самым часто встречающимся значением по столбцу

most_frequent_value = X_train['CouncilArea'].value_counts().index[0] # получаем самое часто встречающееся значение признака CouncilArea
# заполняем наны в столбце CouncilArea полученным значением
X_train['CouncilArea'] = X_train['CouncilArea'].fillna(most_frequent_value)

In [42]:
# заводим KNNImputer. Его же вы будете использовать для заполнения пропусков в тестовых данных
imputer = KNNImputer(n_neighbors=5)
# Обучаем KNNImputer на X_train
imputer.fit(X_train)
# Получаем новый new_X_train — данные как X_train, только без пропусков
new_X_train = imputer.transform(X_train)

ValueError: could not convert string to float: 'Moonee Ponds'

In [43]:
X_train.isna().any()

Suburb           False
Address          False
Rooms            False
Type             False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
YearBuilt        False
CouncilArea      False
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool