In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [3]:
train_data = pd.read_csv("train.csv")
train_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  58036  18387       2     175    75.0    110     70            1     1   
1  88981  23328       2     155    66.0    140     90            1     1   
2  74325  17602       2     168    73.0    120     80            2     1   
3  16519  23432       2     183    95.0    140     90            1     1   
4  28981  23162       1     156    62.0    150     80            1     1   

   smoke  alco  active  cardio  
0      0     0       1       1  
1      1     1       0       0  
2      0     0       1       0  
3      0     0       0       1  
4      0     0       1       1

In [4]:
test_data = pd.read_csv("test.csv")
test_data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0  36043  17646       2     165    65.0    120     80            1     1   
1  44455  20418       1     161    77.0    120     70            1     1   
2  61323  20347       1     165    88.0    120     80            2     2   
3  27780  18086       2     170    91.0    120     80            3     3   
4  54273  21791       1     158    67.0    130     80            1     1   

   smoke  alco  active  cardio  
0      0     0       0       1  
1      0     0       1       1  
2      0     0       1       1  
3      0     0       1       1  
4      0     0       1       1

In [5]:
X_train = train_data.drop(columns=['cardio'])
Y_train = train_data['cardio']

In [6]:
X_test = test_data.drop(columns=['cardio'])
Y_test = test_data['cardio']

In [7]:
logreg = LogisticRegression()

In [8]:
logreg.fit(X_train, Y_train)

D:\Projects_py\Django_NuxtJS\venv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [9]:
y_predicted_logreg = logreg.predict(X_test)

In [10]:
y_predicted_logreg

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [11]:
y_predicted_logreg[:10]

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [12]:
np.array(Y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rf = RandomForestClassifier(n_estimators=20, max_depth=10)

In [15]:
rf.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, n_estimators=20)

In [16]:
y_predicted_rf = rf.predict(X_test)

In [17]:
y_predicted_rf[:10]

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0], dtype=int64)

In [18]:
np.array(Y_test)[:10]

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy_score(y_predicted_logreg, Y_test)

0.6958333333333333

In [21]:
accuracy_score(y_predicted_rf, Y_test)

0.7333333333333333

In [22]:
from sklearn.metrics import f1_score

In [23]:
f1_score(y_predicted_logreg, Y_test)

0.6857782369146006

In [24]:
f1_score(y_predicted_rf, Y_test)

0.7208653175157013