In [71]:
import numpy as np

x = np.array([1, 4, 6, 6, 8])
x

array([1, 4, 6, 6, 8])

In [72]:
type(x)

numpy.ndarray

In [73]:
x.dtype

dtype('int32')

In [74]:
x.size

5

In [75]:
x.ndim

1

In [76]:
x.shape

(5,)

In [77]:
x = np.array([1, 4, 6, 6, 8])
x

array([1, 4, 6, 6, 8])

In [78]:
y = np.array([[1.5, 2, 3], [4, 5, 6]])
y

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [79]:
y[1,2]

6.0

In [80]:
x[3]

6